export const Articles = [
  {
    id: "1",
    name: "Flu",
    description: "",
    category: "Physical Health",
    overview:
      "Influenza, commonly known as 'the flu', is an infectious disease caused by influenza viruses. Symptoms range from mild to severe and often include fever, runny nose, sore throat, muscle pain, headache, coughing, and fatigue. These symptoms begin from one to four days after exposure to the virus and last for about 2–8 days.",
    risks:
      "Flu infection can also worsen long-term health conditions, like heart disease, lung disease, and asthma ",
    diagnosis:
      "*Physical Examination* Your healthcare provider will ask you what symptoms you have and how long you have been sick to determine next steps. Your healthcare provider will also look in your ears, nose, and throat and listen to your lungs with a stethoscope. *Labs and Tests* Rapid influenza tests can be run in the office and takes about 15 minutes to get results. The test typically involves a nasal or throat culture to determine whether influenza A or influenza B is present. The rapid test is far more accurate in infants and becomes less and less accurate the older you get.",
    treatment:
      "*Lifestyle and home remedies* If you do come down with the flu, these measures may help ease your symptoms:•	Drink plenty of liquids. Choose water, juice and warm soups to prevent dehydration. •	Rest. Get more sleep to help your immune system fight infection. You may need to change your activity level, depending on your symptoms. •	Consider pain relievers. Use an over-the-counter pain reliever, such as acetaminophen (Tylenol, others) or ibuprofen (Advil, Motrin IB, others), to combat the achiness associated with influenza. Children and teens recovering from flu-like symptoms should never take aspirin because of the risk of Reye's syndrome, a rare but potentially fatal condition. Your doctor may prescribe an antiviral drug to treat the flu. These drugs can include oseltamivir (Tamiflu), zanamivir (Relenza), peramivir (Rapivab) or baloxavir (Xofluza). These drugs may shorten your illness by a day or so and help prevent serious complications.",
    prevention:
      "Take the time to get your yearly flu shot, especially if you’re around young children or older adults. Getting your vaccination can reduce flu illnesses, visits to the doctor or hospital, and missed work or school. It can also prevent the spread of the flu. https://www.healthline.com/health/flu-risk-factors#older-adults •	practicing clean habits like washing your hands with soap and water •	wiping down surfaces and objects like furniture and toys with disinfectant •	covering coughs and sneezes with tissues to minimize potential infection •	not touching your eyes, nose, and mouth •	getting eight hours of sleep every night •	exercising regularly to improve your immune health",
  },
  {
    id: "2",
    name: "Cluster Headache ",
    description: "",
    category: "Physical Health",
    overview:
      "Cluster headaches, which occur in cyclical patterns or cluster periods, are one of the most painful types of headaches. A cluster headache commonly awakens you in the middle of the night with intense pain in or around one eye on one side of your head.",
    risks:
      "Fortunately, cluster headache is rare and not life-threatening. Treatments can make cluster headache attacks shorter and less severe",
    diagnosis:
      "Cluster headache has a characteristic type of pain and pattern of attacks. A diagnosis depends on your description of the attacks, including your pain, the location and severity of your headaches, and associated symptoms. *Neurological examination* A neurological examination may help your doctor detect physical signs of a neurological disorder. The exam is usually normal in patients with cluster headaches. Your doctor will use a series of procedures to assess your brain function, including testing your senses, reflexes and nerves. *Imaging tests* If you have unusual or complicated headaches or an abnormal neurological examination, your doctor might recommend other tests to rule out other serious causes of head pain, such as a tumor or an aneurysm. Common brain imaging tests include: •	MRI. This uses a powerful magnetic field and radio waves to produce detailed images of your brain and blood vessels. •	CT scan. This uses a series of X-rays to create detailed cross-sectional images of your brain.",
    treatment:
      "There's no cure for cluster headaches. The goal of treatment is to decrease the severity of pain, shorten the headache period and prevent the attacks. Because the pain of a cluster headache comes on suddenly and might subside within a short time, cluster headache can be difficult to evaluate and treat, as it requires fast-acting medications",
    prevention:
      "*Making Lifestyle Changes* •	Limit your intake of alcohol •	Don’t start smoking if you’re a non-smoker. •	Avoid strong-smelling solvents and perfumes. •Engage in light exercise and avoid becoming overheated •	Maintain a normal sleep schedule to reduce your risk. *Seeking Medical Treatment* •	Make an appointment with your doctor if you have a cluster headache •	Ask about sumatriptan to treat pain caused by cluster headaches. •	Look into oxygen therapy to manage pain during a cluster headache. •	Discuss medications that may help to prevent cluster headaches •	Consider transcutaneous vagus nerve stimulation (TVNS).",
  },
  {
    id: "3",
    name: "Stomach Ulcer ",
    description: "",
    category: "Physical Health",
    overview:
      "Stomach ulcers, which are also known as gastric ulcers, are painful sores in the stomach lining. Stomach ulcers are a type of peptic ulcer disease. Peptic ulcers are any ulcers that affect both the stomach and small intestines",
    risks:
      "Most stomach ulcers are not serious and can be easily treated. However, in some cases, a stomach ulcer can lead to more serious problems such as bleeding or perforation (a hole in the lining of the stomach) which can be fatal. The most common risk factor for developing a stomach ulcer is infection with the Helicobacter pylori (H. pylori) bacteria. Other risk factors include: •	NSAIDs: Long-term use of nonsteroidal anti-inflammatory drugs (NSAIDs), such as ibuprofen or aspirin. These drugs can irritate or inflame the stomach lining, making it more susceptible to ulceration. •	Family history: Having a close relative with a history of stomach ulcers increases your risk of developing an ulcer. •	Smoking: Cigarette smoking can damage the protective mucus lining of the stomach and increase acid production, both of which can contribute to the development of ulcers.•	Stress: While stress doesn’t cause stomach ulcers, it may worsen symptoms and increase the risk of complications. If you have any of these risk factors, it’s important to talk to your doctor about ways to reduce your risk of developing a stomach ulcer.",
    diagnosis:
      "Tests and procedures used to diagnose stomach ulcers include: •	Barium swallow: You drink a thick white liquid (barium) that coats your upper gastrointestinal tract and helps your doctor see your stomach and small intestine on X-rays. •	Endoscopy (EGD): A thin, lighted tube is inserted through your mouth and into the stomach and the first part of the small intestine. This test is used to look for ulcers, bleeding, and any tissue that looks abnormal. •	Endoscopic biopsy: A piece of stomach tissue is removed so it can be analyzed in a lab. ",
    treatment:
      "*Healthful diet* it’s possible that some foods play a role in eliminating H. pylori. Foods that may help fight off H. pylori or boost the body’s own healthy bacteria include: •	broccoli, cauliflower, cabbage, and radishes •	leafy greens, such as spinach and kale •	probiotic-rich foods, such as sauerkraut, miso, kombucha, yogurt (especially with lactobacillus and Sacharomyces) •	apples •	blueberries, raspberries, strawberries, and blackberries •	olive oil *Nonsurgical treatment* If your stomach ulcer is the result of H. pylori, you’ll need antibiotics and drugs called proton pump inhibitors (PPIs). PPIs block the stomach cells that produce acid. In addition to these treatments, your doctor may also recommend: •	H2 receptor blockers (drugs that also block acid production) •	stopping use of all NSAIDs •	follow-up endoscopy  •	probiotics (useful bacteria that may have a role in killing off H. pylori) •	bismuth supplement Symptoms of an ulcer may subside quickly with treatment. But even if your symptoms disappear, you should continue to take any medication prescribed by your doctor. *Surgical treatment* •	Surgery may include: •	removal of the entire ulcer •	taking tissue from another part of the intestines and patching it over the ulcer site •	tying off a bleeding artery •	cutting off the nerve supply to the stomach to reduce the production of stomach acid",
    prevention:
      "To prevent the spread of bacteria that might cause a stomach ulcer, wash your hands with soap and water on a regular basis. Also, be sure to properly clean all of your food and to cook it thoroughly as needed. To prevent ulcers caused by NSAIDs, stop using these medications (if possible) or limit their use. If you need to take NSAIDs, be sure to follow the recommended dosage and avoid alcohol while taking these medications. And always take these medications with food and adequate liquids.",
  },
  {
    id: "4",
    name: "Pneumonia",
    description: "infection that affects the air sacs of the lungs",
    category: "Physical Health",
    overview:
      "Pneumonia is an infection that inflames the air sacs in one or both lungs. The air sacs may fill with fluid or pus (purulent material), causing cough with phlegm or pus, fever, chills, and difficulty breathing. A variety of organisms, including bacteria, viruses and fungi, can cause pneumonia.",
    risks:
      "Pneumonia can affect anyone. But the two age groups at highest risk are: •	Children who are 2 years old or younger •	People who are age 65 or older *Other risk factors include:* •	Being hospitalized. You're at greater risk of pneumonia if you're in a hospital intensive care unit, especially if you're on a machine that helps you breathe (a ventilator). •	Chronic disease. You're more likely to get pneumonia if you have asthma, chronic obstructive pulmonary disease (COPD) or heart disease. •	Smoking. Smoking damages your body's natural defenses against the bacteria and viruses that cause pneumonia. •	Weakened or suppressed immune system. People who have HIV/AIDS, who've had an organ transplant, or who receive chemotherapy or long-term steroids are at risk.",
    diagnosis:
      "If pneumonia is suspected, your doctor may recommend the following tests:•	Blood tests. Blood tests are used to confirm an infection and to try to identify the type of organism causing the infection. However, precise identification isn't always possible. •	Chest X-ray. This helps your doctor diagnose pneumonia and determine the extent and location of the infection. However, it can't tell your doctor what kind of germ is causing the pneumonia. •	Pulse oximetry. This measures the oxygen level in your blood. Pneumonia can prevent your lungs from moving enough oxygen into your bloodstream. •	Sputum test. A sample of fluid from your lungs (sputum) is taken after a deep cough and analyzed to help pinpoint the cause of the infection. Your doctor might order additional tests if you're older than age 65, are in the hospital, or have serious symptoms or health conditions. These may include:•	CT scan. If your pneumonia isn't clearing as quickly as expected, your doctor may recommend a chest CT scan to obtain a more detailed image of your lungs. •	Pleural fluid culture. A fluid sample is taken by putting a needle between your ribs from the pleural area and analyzed to help determine the type of infection.",
    treatment:
      "Specific treatments depend on the type and severity of your pneumonia, your age and your overall health. The options include: •	Antibiotics. These medicines are used to treat bacterial pneumonia. It may take time to identify the type of bacteria causing your pneumonia and to choose the best antibiotic to treat it. If your symptoms don't improve, your doctor may recommend a different antibiotic. •	Cough medicine. This medicine may be used to calm your cough so that you can rest. Because coughing helps loosen and move fluid from your lungs, it's a good idea not to eliminate your cough completely. In addition, you should know that very few studies have looked at whether over-the-counter cough medicines lessen coughing caused by pneumonia. If you want to try a cough suppressant, use the lowest dose that helps you rest. •	Fever reducers/pain relievers. You may take these as needed for fever and discomfort. These include drugs such as aspirin, ibuprofen (Advil, Motrin IB, others) and acetaminophen (Tylenol, others).",
    prevention:
      "To help prevent pneumonia: https://www.mayoclinic.org/diseases-conditions/pneumonia/symptoms-causes/syc-20354204 •	Get vaccinated. Vaccines are available to prevent some types of pneumonia and the flu. Talk with your doctor about getting these shots. The vaccination guidelines have changed over time so make sure to review your vaccination status with your doctor even if you recall previously receiving a pneumonia vaccine. •	Make sure children get vaccinated. Doctors recommend a different pneumonia vaccine for children younger than age 2 and for children ages 2 to 5 years who are at particular risk of pneumococcal disease. Children who attend a group child care center should also get the vaccine. Doctors also recommend flu shots for children older than 6 months. •	Practice good hygiene. To protect yourself against respiratory infections that sometimes lead to pneumonia, wash your hands regularly or use an alcohol-based hand sanitizer. •	Don't smoke. Smoking damages your lungs' natural defenses against respiratory infections. •	Keep your immune system strong. Get enough sleep, exercise regularly and eat a healthy diet.",
  },
  {
    id: "5",
    name: "Anxiety",
    description: "",
    category: "Mental Health",
    overview: "",
    risks:
      "These factors may increase your risk of developing an anxiety disorder: •	Trauma. Children who endured abuse or trauma or witnessed traumatic events are at higher risk of developing an anxiety disorder at some point in life. Adults who experience a traumatic event also can develop anxiety disorders. •	Stress due to an illness. Having a health condition or serious illness can cause significant worry about issues such as your treatment and your future. •	Stress buildup. A big event or a buildup of smaller stressful life situations may trigger excessive anxiety — for example, a death in the family, work stress or ongoing worry about finances. •	Personality. People with certain personality types are more prone to anxiety disorders than others are. •	Other mental health disorders. People with other mental health disorders, such as depression, often also have an anxiety disorder. •	Having blood relatives with an anxiety disorder. Anxiety disorders can run in families. •	Drugs or alcohol. Drug or alcohol use or misuse or withdrawal can cause or worsen anxiety.",
    diagnosis:
      "To help diagnose an anxiety disorder, your mental health provider may:•	Give you a psychological evaluation. This involves discussing your thoughts, feelings and behavior to help pinpoint a diagnosis and check for related complications. Anxiety disorders often occur along with other mental health problems — such as depression or substance misuse — which can make diagnosis more challenging. •	Compare your symptoms to the criteria in the DSM-5. Many doctors use the criteria in the Diagnostic and Statistical Manual of Mental Disorders (DSM-5), published by the American Psychiatric Association, to diagnose an anxiety disorder. ",
    treatment:
      "*Psychotherapy* Also known as talk therapy or psychological counseling, psychotherapy involves working with a therapist to reduce your anxiety symptoms. It can be an effective treatment for anxiety *Medications* Several types of medications are used to help relieve symptoms, depending on the type of anxiety disorder you have and whether you also have other mental or physical health issues. For example: •	Certain antidepressants are also used to treat anxiety disorders. •	An anti-anxiety medication called buspirone may be prescribed. •	In limited circumstances, your doctor may prescribe other types of medications, such as sedatives, also called benzodiazepines, or beta blockers. These medications are for short-term relief of anxiety symptoms and are not intended to be used long term.",
    prevention:
      "There's no way to predict for certain what will cause someone to develop an anxiety disorder, but you can take steps to reduce the impact of symptoms if you're anxious: •	Get help early. Anxiety, like many other mental health conditions, can be harder to treat if you wait. •	Stay active. Participate in activities that you enjoy and that make you feel good about yourself. Enjoy social interaction and caring relationships, which can lessen your worries. •	Avoid alcohol or drug use. Alcohol and drug use can cause or worsen anxiety. If you're addicted to any of these substances, quitting can make you anxious. If you can't quit on your own, see your doctor or find a support group to help you.",
  },
  {
    id: "6",
    name: "Anxiety",
    description: "",
    category: "Mental Health",
    overview: "",
    risks:
      "These factors may increase your risk of developing an anxiety disorder: •	Trauma. Children who endured abuse or trauma or witnessed traumatic events are at higher risk of developing an anxiety disorder at some point in life. Adults who experience a traumatic event also can develop anxiety disorders. •	Stress due to an illness. Having a health condition or serious illness can cause significant worry about issues such as your treatment and your future. •	Stress buildup. A big event or a buildup of smaller stressful life situations may trigger excessive anxiety — for example, a death in the family, work stress or ongoing worry about finances. •	Personality. People with certain personality types are more prone to anxiety disorders than others are. •	Other mental health disorders. People with other mental health disorders, such as depression, often also have an anxiety disorder. •	Having blood relatives with an anxiety disorder. Anxiety disorders can run in families. •	Drugs or alcohol. Drug or alcohol use or misuse or withdrawal can cause or worsen anxiety.",
    diagnosis:
      "To help diagnose an anxiety disorder, your mental health provider may:•	Give you a psychological evaluation. This involves discussing your thoughts, feelings and behavior to help pinpoint a diagnosis and check for related complications. Anxiety disorders often occur along with other mental health problems — such as depression or substance misuse — which can make diagnosis more challenging. •	Compare your symptoms to the criteria in the DSM-5. Many doctors use the criteria in the Diagnostic and Statistical Manual of Mental Disorders (DSM-5), published by the American Psychiatric Association, to diagnose an anxiety disorder. ",
    treatment:
      "*Psychotherapy* Also known as talk therapy or psychological counseling, psychotherapy involves working with a therapist to reduce your anxiety symptoms. It can be an effective treatment for anxiety *Medications* Several types of medications are used to help relieve symptoms, depending on the type of anxiety disorder you have and whether you also have other mental or physical health issues. For example: •	Certain antidepressants are also used to treat anxiety disorders. •	An anti-anxiety medication called buspirone may be prescribed. •	In limited circumstances, your doctor may prescribe other types of medications, such as sedatives, also called benzodiazepines, or beta blockers. These medications are for short-term relief of anxiety symptoms and are not intended to be used long term.",
    prevention:
      "There's no way to predict for certain what will cause someone to develop an anxiety disorder, but you can take steps to reduce the impact of symptoms if you're anxious: •	Get help early. Anxiety, like many other mental health conditions, can be harder to treat if you wait. •	Stay active. Participate in activities that you enjoy and that make you feel good about yourself. Enjoy social interaction and caring relationships, which can lessen your worries. •	Avoid alcohol or drug use. Alcohol and drug use can cause or worsen anxiety. If you're addicted to any of these substances, quitting can make you anxious. If you can't quit on your own, see your doctor or find a support group to help you.",
  },
];
