const locationSymptoms = [
  {
    id: 0,
    title: "Cough",
    description: "dfsdf",
    common: true,
    category: "Physical",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },

  {
    id: 1,
    title: "Headache",
    description: "dfsdf",
    common: true,
    category: "Physical",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Monkey Pox"],
  },
  {
    id: 2,
    title: "Sore throat",
    description: "dfsdf",
    common: true,
    category: "Physical",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Monkey Pox"],
  },
  {
    id: 3,
    title: "Stomach pain",
    description: "dfsdf",
    common: true,
    category: "Physical",
    diseases: ["Migraine", "Bile Reflux"],
  },
  {
    id: 7,
    title: "Chills",
    category: "Physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Monkey Pox"],
  },
  {
    id: 8,
    title: "Fatigue",
    category: "Physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis"],
  },
  {
    id: 9,
    title: "Nausea",
    category: "Physical",
    description: "",
    diseases: ["Migraine", "Cholera"],
  },
  {
    id: 10,
    title: "Vomiting",
    category: "Physical",
    description: "",
    diseases: ["Bile Reflux", "Migraine", "Cholera"],
  },
  {
    id: 11,
    title: "Diarrhea",
    category: "Physical",
    description: "",
    diseases: ["Cholera"],
  },
  {
    id: 12,
    title: "Loss of taste or smell",
    category: "Physical",
    description: "",
    diseases: ["Covid-19"],
  },
  {
    id: 13,
    title: "Chest pain",
    category: "Physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 14,
    title: "Shortness of breath",
    category: "Physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 15,
    title: "Muscle pain",
    category: "Physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 16,
    title: "Fever",
    category: "Physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 17,
    title: "Sneezing",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 18,
    title: "Runny nose",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 19,
    title: "Sore throat",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 20,
    title: "Congestion",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 21,
    title: "Watery eyes",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 22,
    title: "Itchy eyes",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 23,
    title: "Itchy nose",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 24,
    title: "Itchy throat",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 25,
    title: "Itchy skin",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 26,
    title: "Itchy ears",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 27,
    title: "Itchy mouth",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 28,
    title: "Rash on skin",
    category: "Physical",
    description: "",
    diseases: ["Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 29,
    title: "Discoloration of finger or toes",
    category: "Physical",
    description: "",
    diseases: ["Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 30,
    title: "Red irritated eyes",
    category: "Physical",
    description: "",
    diseases: ["Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 31,
    title: "Loss of appetite",
    category: "Physical",
    description: "",
    diseases: ["Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 32,
    title: "Sweating",
    category: "Physical",
    description: "",
    diseases: ["Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 33,
    title: "Weight loss",
    category: "Physical",
    description: "",
    diseases: ["Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 34,
    title: "Night sweats",
    category: "Physical",
    description: "",
    diseases: ["Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 35,
    title: "Swellings",
    category: "Physical",
    description: "",
    diseases: ["Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 36,
    title: "Heartburn",
    category: "Physical",
    description: "",
    diseases: ["Bile Reflux"],
  },
  {
    id: 37,
    title: "Trouble swallowing",
    category: "Physical",
    description: "",
    diseases: ["Bile Reflux"],
  },
  {
    id: 38,
    title: "Asthma",
    category: "Physical",
    description: "",
    diseases: ["Bile Reflux"],
  },
  {
    id: 39,
    title: "Coughing up blood",
    category: "Physical",
    description: "",
    diseases: ["Bile Reflux"],
  },
  {
    id: 40,
    title: "Poor concentration",
    category: "Mental",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 41,
    title: "feeling very hot or very cold",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 42,
    title: "joint pain",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 43,
    title: "Joint restriction",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 44,
    title: "Joint swelling",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 45,
    title: "Swollen lymph nodes",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 46,
    title: "Aching muscles and backaches",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 47,
    title: "Muscle weakness",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 48,
    title: "common cold",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 49,
    title: "Sore throat",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 50,
    title: "Polyps (growths)",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 51,
    title: "Nasal congestion",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 52,
    title: "deviated septum",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 53,
    title: "Post nasal",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 54,
    title: "Nasal discharge",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 55,
    title: "Nasal obstruction",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 56,
    title: "Facial pressure",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 57,
    title: "Halitosis",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
  {
    id: 58,
    title: "Shock",
    category: "physical",
    description: "",
    diseases: ["Covid-19", "Flu", "Tuberculosis", "Sinuses", "Bile Reflux"],
  },
];

export default locationSymptoms;
